### PR TITLE
fix: channel feeds should be `url` not `id`

### PR DESCRIPTION
**Pull request by jtgi**
hot chocolates are mid

### CODE REVIEW

**Comment by gskril** [comment]
not merging because you insulted hot chocolate 😡

**Comment by gskril** [comment]
but the real reason I chose `id` instead of `url` is because technically the protocol allows any string as a `parent_url` as long as it's unique, so `id` felt more appropriate

see this query (first one on page 5) for examples https://dune.com/queries/3334932/5587582

**Comment by jtgi** [comment]
> but the real reason I chose `id` instead of `url` is because technically the protocol allows any string as a `parent_url` as long as it's unique, so `id` felt more appropriate
> 
> see this query (first one on page 5) for examples https://dune.com/queries/3334932/5587582

makes sense, I should have added to description: the implementation currently expects `url` and fails on `id`. Thought it was a documentation error.

```sh
$ curl -s "https://feeds.fcstr.xyz/rss/channel?url=chain://eip155:7777777/erc721:0x4f86113fc3e9783cf3ec9a552cbb566716a57628" | head -n 10
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0">
    <channel>
        <title>Farcaster Channel</title>
        <link>chain://eip155:7777777/erc721:0x4f86113fc3e9783cf3ec9a552cbb566716a57628</link>
        <description>undefined</description>
        <lastBuildDate>Sun, 07 Jan 2024 23:44:57 GMT</lastBuildDate>
        <docs>https://validator.w3.org/feed/docs/rss2.html</docs>
        <generator>https://github.com/jpmonette/feed</generator>
        <item>
$ curl -s "https://feeds.fcstr.xyz/rss/channel?id=chain://eip155:7777777/erc721:0x4f86113fc3e9783cf3ec9a552cbb566716a57628" | jq . 
{
  "issues": [
    {
      "code": "invalid_type",
      "expected": "string",
      "received": "undefined",
      "path": [
        "url"
      ],
      "message": "Required"
    }
  ],
  "name": "ZodError"
}
```

**Comment by jtgi** [comment]
had an extra couple minutes, feel free to do what you want with it: https://github.com/gskril/farcaster-hub-feeds/pull/3

**Comment by gskril** [comment]
oohh oops I see, you're right. I do think `id` would have been better but it's already launched so want to avoid a breaking change. Going to merge this and close the other. Thanks for catching it!

**Pull request merged**
